# A Demo For Jupyter

In [1]:
import matplotlib
import numpy as np
import pandas as pd
from lmfit import Parameters, minimize
from matplotlib import pyplot as plt
import matplotlib as mpl
%matplotlib inline
from scipy import integrate, interpolate, linalg, odr, optimize, signal, stats

In [2]:
print('this is a string' + ' this is another string')
print('you can multiply strings' * 2)
print('a')
print('b')

this is a string this is another string
you can multiply stringsyou can multiply strings
a
b


In [3]:
# make an array
a = [[1, 2, 3], [4, 5, 6]]
a.append([2, 3, 4])  # append additional lists
b = np.zeros((2, 3), int)
print(a, b, type(a), type(b))
print('---------------')

# add two lists together, note b is np.ndarray not list so conversion is needed
a = np.asarray(a, int)
c = np.array([[6, 7, 8], [7, 8, 9]])
c = c.T  # translate an array by switching its dimensions
print(c)
print('---------------')
# append ndarrays, note axis = 0 means the along the rows, axis = 1 means along the columns, etc.
d = np.append(a, b, axis=0)
print(d)
print('---------------')
# concatenate also works, for a sequence of arrays
e = np.concatenate((a, b.T, c), axis=1)

print(e)
print('---------------')

# we can also perform calculations on arrays directly
e / 30
np.divide(e, 30)  # can also use this for element division in arrays


[[1, 2, 3], [4, 5, 6], [2, 3, 4]] [[0 0 0]
 [0 0 0]] <class 'list'> <class 'numpy.ndarray'>
---------------
[[6 7]
 [7 8]
 [8 9]]
---------------
[[1 2 3]
 [4 5 6]
 [2 3 4]
 [0 0 0]
 [0 0 0]]
---------------
[[1 2 3 0 0 6 7]
 [4 5 6 0 0 7 8]
 [2 3 4 0 0 8 9]]
---------------


array([[0.03333333, 0.06666667, 0.1       , 0.        , 0.        ,
        0.2       , 0.23333333],
       [0.13333333, 0.16666667, 0.2       , 0.        , 0.        ,
        0.23333333, 0.26666667],
       [0.06666667, 0.1       , 0.13333333, 0.        , 0.        ,
        0.26666667, 0.3       ]])

In [ ]:
# element-wise operations
array1 = np.arange(2, 10001, 2)
array2 = array1 - 1
array3 = array1 + 1
# array1 = (2,4,6)
# array2 = (1,3,5)
np.prod(array1/array2) * np.prod(array1/array3) * \
    2  # Wallis product: should be Pi

In [ ]:
# for pandas
# Series is just 1-d data tables
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s